### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [alcoelho/EDL#1]
Fiz alguns comentário no seu commit, mas o texto está bem escrito.

**Comment by marjorinec** [comment]
@fsantanna 

Bom dia, professor.

Perdão pela demora para resposta.
Descobri depois que existem essas linguagens de sintaxe mais simples/clara
para js, são bem convenientes por serem mais legíveis e prevenirem alguns
problemas de js. Obrigada pelo aviso.
Com "mais tolerante que Ruby" eu quis dizer que js é mais tolerante com
operações e tipos de variáveis - ele permite operações com variáveis de
tipos diferentes.
Não entendi a mensagem sobre exemplo de trade-off.
E também, havia bonificação por entregar o artigo antes do prazo? Eu
entreguei exatamente na data informada porque era o prazo, senão teria dado
upload antes.

Att.
Alline

**Comment by fsantanna** [comment]
O quanto antes vocês mandarem, mais tenho chances de opinar e dar dicas (e mais vocês estudam/aprendem). Por isso a bonificação.
Exemplo de trade off: chamadas assíncronas são mais responsivas, porém menos legíveis.
O que é melhor, responsividade ou legibilidade? R. Depende. Isso é um exemplo de trade off: ganha-se de um lado, perde-se de outro, mas sem um veredito.
